### ISSUE TITLE
which zig compiler

### ISSUE THREAD

**Issue by wilsonk** [davidgm94/RNU#48]
Hello, is there a specific zig compiler version you are using? I tried to build a couple weeks ago, as well as again today, and things didn't build.

Could you add the version to the README as well, just so others will know which compiler version to use ;)

Thanks

**Comment by davidgmbb** [comment]
Hello,
Thank you for your interest in the project. I am using last master (last binary uploaded at the website). That's the one being used in the CI as well. You should be able to build without problems with that one. I'll add that immediately, thanks for the report :)
